[Interface]
Address = 10.13.17.1/24
ListenPort = 51820
PrivateKey = uFGQ6ENmlT5f+p3ZYNK+7k1FZ+E/blWQthiVil0YHWA=
PostUp = iptables -t nat -A POSTROUTING -s 10.13.17.0/24 ! -d 10.13.17.0/24 -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -s 10.13.17.0/24 ! -d 10.13.17.0/24 -j MASQUERADE
