[Interface]
Address = 10.13.16.1/24
ListenPort = 51820
PrivateKey = YJsQQz/xZDrehZSl/CNQJhrZT/9p8RJDuSgEahAtlFE=
PostUp = iptables -t nat -A POSTROUTING -s 10.13.16.0/24 ! -d 10.13.16.0/24 -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -s 10.13.16.0/24 ! -d 10.13.16.0/24 -j MASQUERADE
