[Interface]
Address = 10.13.15.1/24
ListenPort = 51820
PrivateKey = EKSOT0H/EGKsCFoFA1iYiRYR43VX/aEHGYn/QfNZUEs=
PostUp = iptables -t nat -A POSTROUTING -s 10.13.15.0/24 ! -d 10.13.15.0/24 -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -s 10.13.15.0/24 ! -d 10.13.15.0/24 -j MASQUERADE
