[Interface]
PrivateKey = WJC0KZjD4knUKhixmkOJblemjUjYH/YI2D2E/UhojEc=
Address = 10.13.13.2/32

[Peer]
PublicKey = rKCjjZR5cgoZSG0BE1Cjs5wHcOAOYU5Vweb/Gj0rPWg=
Endpoint = 127.0.0.1:21820
AllowedIPs = 10.13.13.0/24, 172.16.0.0/12
PersistentKeepalive = 25
