#!/usr/bin/env node
/**
 * Creates the product and the two prices this app sells, in a Stripe test-mode
 * account, and prints the .env lines that point at them.
 *
 * It exists because the price ids are the one part of the billing configuration
 * that cannot be defaulted: they are generated by the provider, they differ per
 * account, and the app cannot start a checkout without them. Copying them out of
 * the dashboard by hand is where `no price configured for plan` comes from.
 *
 * Usage:
 *   pnpm billing:prices                     read STRIPE_API_KEY from .env
 *   pnpm billing:prices --key sk_test_...    use this key instead
 *   pnpm billing:prices --currency usd       default is brl
 *
 * Idempotent: prices carry a lookup_key, so a second run finds them instead of
 * creating a second pair. Refuses any key that is not sk_test_ — this script
 * writes to whatever account the key belongs to.
 */

import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const API = 'https://api.stripe.com';
const PRODUCT_ID = 'poc_vpn_pro';

const PRICES = [
	{ cadence: 'monthly', interval: 'month', amount: 2990, lookupKey: 'poc_vpn_pro_monthly' },
	{ cadence: 'yearly', interval: 'year', amount: 29900, lookupKey: 'poc_vpn_pro_yearly' },
];

const ENV_VAR_BY_CADENCE = { monthly: 'STRIPE_PRICE_ID', yearly: 'STRIPE_PRICE_ID_YEARLY' };

function argOf(name) {
	const index = process.argv.indexOf(`--${name}`);
	return index === -1 ? undefined : process.argv[index + 1];
}

function keyFromDotenv() {
	for (const file of ['.env.local', '.env']) {
		const path = join(ROOT, file);
		if (!existsSync(path)) continue;

		const match = /^STRIPE_API_KEY=(.*)$/m.exec(readFileSync(path, 'utf8'));
		const value = match?.[1]?.trim().replace(/^["']|["']$/g, '');
		if (value) return value;
	}
	return undefined;
}

function die(message) {
	process.stderr.write(`\n${message}\n\n`);
	process.exit(1);
}

const apiKey = argOf('key') ?? process.env['STRIPE_API_KEY'] ?? keyFromDotenv();
const currency = argOf('currency') ?? 'brl';

if (!apiKey) {
	die('no STRIPE_API_KEY: pass --key sk_test_... or put one in .env');
}
if (!apiKey.startsWith('sk_test_')) {
	die(
		`refusing a key that is not sk_test_ (got ${apiKey.slice(0, 8)}...): this script writes data`,
	);
}
if (apiKey === 'sk_test_local') {
	die(
		'sk_test_local is the localstripe placeholder, not a Stripe account key.\n' +
			'Get one from dashboard.stripe.com in test mode. See docs/06-AMBIENTE-LOCAL.md.',
	);
}

async function call(method, path, body, tolerate = []) {
	const response = await fetch(`${API}${path}`, {
		method,
		headers: {
			Authorization: `Bearer ${apiKey}`,
			...(body ? { 'Content-Type': 'application/x-www-form-urlencoded' } : {}),
		},
		...(body ? { body: new URLSearchParams(body).toString() } : {}),
	});

	const payload = await response.json();
	if (response.ok) return payload;

	const error = payload?.error ?? {};
	if (tolerate.includes(response.status) || tolerate.includes(error.code)) return undefined;

	die(`${method} ${path} -> ${response.status}: ${error.message ?? JSON.stringify(payload)}`);
}

async function findPrice(lookupKey) {
	const found = await call('GET', `/v1/prices?lookup_keys[]=${lookupKey}&active=true&limit=1`);
	return found?.data?.[0];
}

async function ensureProduct() {
	const existing = await call('GET', `/v1/products/${PRODUCT_ID}`, undefined, [404]);
	if (existing?.id) return existing.id;

	await call('POST', '/v1/products', { id: PRODUCT_ID, name: 'poc-vpn Pro' }, [
		'resource_already_exists',
	]);
	return PRODUCT_ID;
}

const lines = [];

process.stdout.write(`\nstripe test mode, currency ${currency}\n\n`);

const product = await ensureProduct();

for (const price of PRICES) {
	const existing = await findPrice(price.lookupKey);

	if (existing) {
		process.stdout.write(`  reused  ${price.cadence.padEnd(7)} ${existing.id}\n`);
		lines.push(`${ENV_VAR_BY_CADENCE[price.cadence]}=${existing.id}`);
		continue;
	}

	const created = await call('POST', '/v1/prices', {
		product,
		currency,
		unit_amount: String(price.amount),
		'recurring[interval]': price.interval,
		lookup_key: price.lookupKey,
		nickname: `poc-vpn pro ${price.cadence}`,
	});

	if (!created?.id) die(`Stripe accepted the ${price.cadence} price but returned no id`);

	process.stdout.write(`  created ${price.cadence.padEnd(7)} ${created.id}\n`);
	lines.push(`${ENV_VAR_BY_CADENCE[price.cadence]}=${created.id}`);
}

process.stdout.write(`\nput these in .env:\n\n${lines.join('\n')}\n\n`);
process.stdout.write(
	'then, with BILLING_DRIVER=stripe and STRIPE_API_BASE unset:\n' +
		`  stripe listen --forward-to localhost:${process.env['API_PORT'] ?? 3000}/billing/webhook\n` +
		'and put the whsec_... it prints in STRIPE_WEBHOOK_SECRET.\n\n',
);
